FROM python:3.13-slim

WORKDIR /app

# Copy dependency requirements and install them
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application files
COPY . .

# Run the background worker daemon
CMD ["python", "src/BackgroundWorkers/worker.py"]